<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <a href="/">HOMEPAGE </a><br/>
    <h1 >Aggiunta libro</h1>
    <form action="/form" method="post">
        <input type="text" name="autore" placeholder="Inserisci autore" /><br/><br/>
        <input type="text" name="titolo" placeholder="Inserisci titolo" /><br/><br/>
        <input type="number" name="anno" placeholder="Inserisci anno" /><br/><br/>
        <input type="submit" value="Salva" /><br/>


    </form>



</body>
</html>